services:
  react-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"  
    volumes:
      - ./src:/app/src              
      - ./public:/app/public       
      - ./index.html:/app/index.html
      - /app/node_modules          
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0

  react-app-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production