ARG USERNAME=user123
ARG USER_UID=1001
ARG USER_GID=$USER_UID

FROM node:24.6-alpine

ARG USERNAME
ARG USER_UID
ARG USER_GID

RUN addgroup -g ${USER_GID} -S ${USERNAME} && \
    adduser -S ${USERNAME} -u ${USER_UID} -G ${USERNAME}

WORKDIR /app

RUN chown ${USERNAME}:${USERNAME} /app

COPY --chown=${USERNAME}:${USERNAME} package*.json ./

USER ${USERNAME}

RUN npm install 

COPY --chown=${USERNAME}:${USERNAME} . .

EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
